In [3]:
# Q1
'''
- 단어 길이 벡터화
주어진 문장에서 각 단어의 길이를 추출하여 NumPy 배열로 변환하는 간단한 NLP 전처리 예제
단어 리스트: ['NumPy', 'makes', 'numerical', 'computing', 'easy', 'and', 'fast']
단어 길이 벡터: [5 5 9 9 4 3 4]
'''
import numpy as np

txt = "NumPy makes numerical computing easy and fast"
words = txt.split()
word_lengths = np.array([len(word) for word in words])
print("단어 리스트:", words)
print("단어 길이 벡터:", word_lengths)

단어 리스트: ['NumPy', 'makes', 'numerical', 'computing', 'easy', 'and', 'fast']
단어 길이 벡터: [5 5 9 9 4 3 4]


In [4]:
# Q2
'''
- 감정 점수 평균
영화 리뷰나 트윗에 부여된 감정 점수 배열의 평균과 분산을 NumPy로 계산하는 예제
감정 점수: 1(부정) ~ 10(긍정)
감정 점수: [8 9 7 6 10 5 4]
평균: 7.0
분산: 4.0
'''
import numpy as np

sentimentScores = [8, 9, 7, 6, 10, 5, 4]
print("감정 점수:", np.array(sentimentScores))
print("평균:", np.mean(sentimentScores))
print("분산:", np.var(sentimentScores))

감정 점수: [ 8  9  7  6 10  5  4]
평균: 7.0
분산: 4.0


In [5]:
# Q3
'''
- 행렬 전치 연습
챗봇의 입력과 응답 데이터를 배열로 처리하며, 전치를 이용해 열 중심의 분석도 가능하게 함
입력(질문)과 출력(답변) 쌍
"안녕", "안녕하세요"
"이름이 뭐야?", "저는 챗봇이에요"
"날씨 어때?", "오늘은 맑아요"
전치 (행 <-> 열 전환)
'''
import numpy as np

sentence = ['안녕', '안녕하세요', '이름이 뭐야?', '저는 챗봇이에요', '날씨 어때?', '오늘은 맑아요']
np_sentence = np.array(sentence)
reshaped = np_sentence.reshape(3, 2)
transposed = reshaped.T
print("원본:")
print(f"{sentence}\n")
print("numpy배열로 변환:")
print(f"{np_sentence}\n")
print("n행 n열로 변경:")
print(f"{reshaped}\n")
print("행과 열 바꾸기")
print(f"{transposed}")

원본:
['안녕', '안녕하세요', '이름이 뭐야?', '저는 챗봇이에요', '날씨 어때?', '오늘은 맑아요']

numpy배열로 변환:
['안녕' '안녕하세요' '이름이 뭐야?' '저는 챗봇이에요' '날씨 어때?' '오늘은 맑아요']

n행 n열로 변경:
[['안녕' '안녕하세요']
 ['이름이 뭐야?' '저는 챗봇이에요']
 ['날씨 어때?' '오늘은 맑아요']]

행과 열 바꾸기
[['안녕' '이름이 뭐야?' '날씨 어때?']
 ['안녕하세요' '저는 챗봇이에요' '오늘은 맑아요']]


In [6]:
# Q4
'''
- 단어 등장 빈도 계산
문장에서 단어의 등장 횟수를 계산해 배열로 표현. 단어를 정렬해 시각화하기 쉬움.
txt = "Hello world hello numpy world hello ai"
단어: ['ai', 'hello', 'numpy', 'world']
빈도: [1 3 1 2]
'''
import numpy as np
from collections import Counter

txt = "Hello world hello numpy world hello ai"
words = txt.lower().split()
word_counts = Counter(words)
print(f"{word_counts}\n")

unique_words = sorted(word_counts.keys())
frequence = np.array([word_counts[word] for word in unique_words])
print("단어:", unique_words)
print("빈도:", frequence)

Counter({'hello': 3, 'world': 2, 'numpy': 1, 'ai': 1})

단어: ['ai', 'hello', 'numpy', 'world']
빈도: [1 3 1 2]


In [7]:
# Q5
'''
- 이미지 픽셀 밝기 조정
NumPy로 이미지 픽셀 밝기 조정(어둡게 or 밝게) - 이미지 배열 요소에 스칼라 연산 수행
'''
import numpy as np

image = np.array([[100, 120, 130], [150, 160, 170], [200, 220, 240]])
print(image)
brighter_image = np.clip(image + 20, 0, 255)
print(brighter_image)

[[100 120 130]
 [150 160 170]
 [200 220 240]]
[[120 140 150]
 [170 180 190]
 [220 240 255]]


In [33]:
# Q6
'''
- 코사인 유사도 계산
문장 또는 사용자 프로필 간의 벡터 유사도를 계산하는 데 자주 사용됨
[1, 2, 3]
[2, 4, 6]
코사인 유사도 = (A, B) / (||A|| * ||B||)
                 내적   /      크기
cos_sim = np.dot(vec1, vec2) / (np.linalg.norm(vec1) * np.linalg.norm(vec2))
'''
import numpy as np

vec1 = np.array([1, 2, 3])
vec2 = np.array([2, 4, 6])
cos_sim = np.dot(vec1, vec2) / (np.linalg.norm(vec1) * np.linalg.norm(vec2))
print("코사인 유사도:", cos_sim)

코사인 유사도: 1.0


In [23]:
# Q7
'''
- Bag-of-Words 벡터 처리
여러 문장에 등장하는 단어들을 기반으로 Bag-of-Words(BoW) 행렬을 NumPy로 직접 생성해보는 NLP 전처리 예제
'''
import numpy as np

# 세 개의 문장을 정의
sentences = ["hello world",
             "hello numpy",
             "hello ai world"]

# 모든 문장에서 단어를 추출하여 유니크한 단어 집합 생성
all_words = set(word for sentence in sentences for word in sentence.split())

# 단어별 인덱스를 부여하여 딕셔너리를 생성
word_index = {word: idx for idx, word in enumerate(sorted(all_words))}
print(f"{word_index}\n")

# 문장 수 x 단어 수 크기의 BoW 행렬 초기화
bow_matrix = np.zeros((len(sentences), len(word_index)))
print(f"{bow_matrix}\n")

# 각 문장에서 단어 등장 횟수를 세어 BoW 행렬을 채움
for i, sentence in enumerate(sentences):
  for word in sentence.split():
    idx = word_index[word]
    bow_matrix[i, idx] += 1
print(bow_matrix)

{'ai': 0, 'hello': 1, 'numpy': 2, 'world': 3}

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[0. 1. 0. 1.]
 [0. 1. 1. 0.]
 [1. 1. 0. 1.]]


In [9]:
# Q8
'''
- 간단한 채팅 로그 분석
챗봇 로그 데이터를 NumPy 배열로 만들어 대화 수, 길이 평균 등을 분석해보는 예제
chat_logs = [["안녕", "안녕하세요! 무엇을 도와드릴까요?"],
            ["오늘 날씨 어때?", "오늘은 맑고 따뜻한 날씨입니다."],
            ["시간 좀 알려줘", "현재 시간은 오후 3시입니다."]]
'''
import numpy as np

chat_logs = [["안녕", "안녕하세요! 무엇을 도와드릴까요?"],
            ["오늘 날씨 어때?", "오늘은 맑고 따뜻한 날씨입니다."],
            ["시간 좀 알려줘", "현재 시간은 오후 3시입니다."]]

np_chat_logs = np.array(chat_logs)
user_lengths = np.array([len(q) for q in np_chat_logs[:, 0]])
bot_lengths = np.array([len(a) for a in np_chat_logs[:, 1]])

print("사용자 평균 입력 길이:", np.mean(user_lengths))
print("챗봇 평균 응답 길이:", np.mean(bot_lengths))

사용자 평균 입력 길이: 6.333333333333333
챗봇 평균 응답 길이: 17.0
